/*
 * Wave bands for the hero.
 *
 * Each band is a Gerstner (trochoidal) surface: a sum of components whose
 * wavelengths all divide the tile exactly.  Two consequences matter here.
 *
 *   1. Periodicity is exact.  x(0) and x(T) differ by exactly T, and y(0)
 *      equals y(T) with the same slope, so scrolling the tiling by one tile
 *      loops with no seam and no drift.
 *   2. It is not a sine.  The horizontal term bunches points at the crests, so
 *      crests come up narrow and troughs stay long and flat, the way water
 *      actually sits.  A plain sine reads as a ribbon.
 *
 * Three components per band, at coprime-ish harmonics, put the repeat far
 * enough out that the eye does not catch it.
 *
 * Run: node tools/build-waves.mjs
 */
import { writeFileSync } from "node:fs";
import { V, fitPath, chainToD, fmt } from "./geom.mjs";

const TILE = 1440;   // design units per tile
const TILES = 3;     // scrolling by 1/3 of the strip advances exactly one tile

/** steepness: how far the crests bunch. Must keep sum(Q*A*k) below 1. */
const BANDS = [
  {
    name: "far",
    depth: 120,
    steepness: 1.45,
    parts: [
      { n: 2, amp: 15, phase: 0.0 },
      { n: 3, amp: 7, phase: 2.2 },
      { n: 7, amp: 3, phase: 4.6 },
    ],
  },
  {
    name: "mid",
    depth: 140,
    steepness: 1.15,
    parts: [
      { n: 2, amp: 18, phase: 0.9 },
      { n: 5, amp: 7, phase: 3.1 },
      { n: 8, amp: 3, phase: 5.4 },
    ],
  },
  {
    name: "near",
    depth: 170,
    steepness: 1.3,
    parts: [
      { n: 2, amp: 26, phase: 2.4 },
      { n: 3, amp: 11, phase: 0.3 },
      { n: 7, amp: 4, phase: 4.9 },
    ],
  },
  {
    // The waterline itself: the beach the page's content sits on.
    name: "shore",
    depth: 220,
    steepness: 1.5,
    parts: [
      { n: 1, amp: 10, phase: 3.7 },
      { n: 4, amp: 5, phase: 1.4 },
      { n: 9, amp: 2, phase: 5.9 },
    ],
  },
];

const build = (band) => {
  const parts = band.parts.map((p) => ({ ...p, k: (2 * Math.PI * p.n) / TILE }));
  const drift = parts.reduce((s, p) => s + band.steepness * p.amp * p.k, 0);
  if (drift >= 0.92) {
    throw new Error(`${band.name}: steepness ${drift.toFixed(2)} folds the surface over`);
  }

  const ampTotal = parts.reduce((s, p) => s + p.amp, 0);
  const base = ampTotal + 10;                 // mean water level inside the viewBox
  const height = Math.round(base + band.depth);
  const span = TILE * TILES;

  // theta parametrises the surface; x lags it by the horizontal Gerstner term.
  const xOf = (t) => t - parts.reduce((s, p) => s + band.steepness * p.amp * Math.sin(p.k * t + p.phase), 0);
  const yOf = (t) => base - parts.reduce((s, p) => s + p.amp * Math.cos(p.k * t + p.phase), 0);
  const x0 = xOf(0);
  const at = (t) => [xOf(t) - x0, yOf(t)];

  const STEPS = 2400;
  const pts = Array.from({ length: STEPS + 1 }, (_, i) => at((span * i) / STEPS));
  const tangents = (i) =>
    V.norm(V.sub(pts[Math.min(STEPS, i + 1)], pts[Math.max(0, i - 1)]));
  const chain = fitPath(pts, tangents, 0.6);

  // The boat locates a surface height by x. Preserve a single-valued curve
  // through fitting and serialization, not only in the analytic Gerstner sum.
  for (const seg of chain) {
    const xs=[seg.p0,seg.c1,seg.c2,seg.p3].map(p=>+p[0].toFixed(2));
    if(xs.some((x,i)=>i>0 && x<xs[i-1]))
      throw new Error(`${band.name}: fitted surface folds backward in x`);
  }
  const body = `M${fmt(pts[0])}${chainToD(chain)}L${span},${height}L0,${height}Z`;

  return {
    name: band.name,
    viewBox: `0 0 ${span} ${height}`,
    height,
    body,
    segments: chain.length,
    // sanity: the ends must coincide in height and land exactly one span apart
    seamDy: +(pts[STEPS][1] - pts[0][1]).toFixed(6),
    seamDx: +(pts[STEPS][0] - span).toFixed(6),
  };
};

const bands = BANDS.map(build);

const ts = `/* Generated by tools/build-waves.mjs — edit the bands there, not this file. */

export type WaveBandName = "far" | "mid" | "near" | "shore";

export type WaveBand = {
  name: string;
  viewBox: string;
  /** The water body: surface curve closed down to the foot of the viewBox.
   *  Foam is a second copy of this shifted up a few units, not a stroke —
   *  stroking a long fitted curve leaves a visible bead at every join. */
  body: string;
};

/** The strip is ${TILES} tiles wide, so translating it by
 *  -${(100 / TILES).toFixed(4)}% of its own width advances exactly one tile,
 *  whatever width the CSS gives it. */
export const TILE_COUNT = ${TILES};

export const WAVE_BANDS: Record<WaveBandName, WaveBand> = {
${bands
  .map(
    (b) => `  ${b.name}: {
    name: ${JSON.stringify(b.name)},
    viewBox: ${JSON.stringify(b.viewBox)},
    body:
      ${JSON.stringify(b.body)},
  },`,
  )
  .join("\n")}
};
`;

writeFileSync(new URL("../components/wave-paths.ts", import.meta.url), ts);
console.log(
  bands
    .map((b) => `${b.name.padEnd(5)} h=${String(b.height).padStart(3)} segs=${String(b.segments).padStart(3)} seam dy=${b.seamDy} dx=${b.seamDx}`)
    .join("\n"),
);
